admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

cvtheque:
    resource: "@CvthequeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
