ct_cv_theque_homepage:
    path:     /
    defaults: { _controller: CtCvThequeBundle:Default:index }

ct_cv_theque_experiences:
    path:   /experiences
    defaults: { _controller: CtCvThequeBundle:Default:experiences}
    
ct_cv_theque_identite:
    path:   /identite
    defaults: { _controller: CtCvThequeBundle:Default:identite}
    
ct_cv_theque_competences:
    path:   /competences
    defaults: { _controller: CtCvThequeBundle:Default:competences}