AdminBundle\Entity\Hobbies:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hoType:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
